# Generated by Django 5.1.1 on 2024-09-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diaryentry_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'verbose_name': 'Запись в дневнике', 'verbose_name_plural': 'Записи в дневнике'},
        ),
        migrations.RemoveField(
            model_name='diaryentry',
            name='owner',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary/', verbose_name='Изображение'),
        ),
    ]
