# Generated by Django 4.2.2 on 2024-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_diaryentry_options_diaryentry_date_of_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date_of_event',
            field=models.DateField(blank=True, help_text='в формате ГГ-ММ-ДД', null=True, verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание события'),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Заголовок'),
        ),
    ]
