# Generated by Django 5.1.1 on 2024-09-22 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diaryentry_options_remove_diaryentry_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='date_of_event',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата события'),
        ),
    ]
