# Generated by Django 4.2.2 on 2024-10-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_diaryentry_date_of_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diaryentry',
            options={'ordering': ('name', 'date_of_event'), 'permissions': [('can_edit_name', 'Can edit name'), ('can_edit_description', 'Can edit description'), ('can_edit_date_of_view', 'Can edit date of view'), ('can_edit_image', 'Can edit image')], 'verbose_name': 'Запись в дневнике', 'verbose_name_plural': 'Записи в дневнике'},
        ),
    ]
