# Generated by Django 5.1.1 on 2024-09-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diaryentry_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date_of_event',
            field=models.DateField(blank=True, null=True, verbose_name='Дата события'),
        ),
    ]
