# Generated by Django 4.2.2 on 2024-09-28 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_diaryentry_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date_of_event',
            field=models.DateField(blank=True, help_text='в формате 2024-01-31', null=True, verbose_name='Дата события'),
        ),
    ]
