# Generated by Django 4.2.2 on 2024-09-28 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_alter_diaryentry_date_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diaryentry',
            name='date_of_event',
            field=models.DateField(default='2024-01-01', help_text='в формате 2024-01-31', verbose_name='Дата события'),
        ),
    ]
